source 'https://rubygems.org'

gem 'minitest'
gem 'rake'
gem 'rspec-core'
gem 'rubocop', require: false
gem 'rubocop-minitest', require: false
gem 'rubocop-rake', require: false
gem 'simplecov', require: false, group: :test
