source 'https://rubygems.org'

gem 'rake'
gem 'rspec', '~> 3.0'
gem 'rubocop', require: false
gem 'rubocop-rake', require: false
gem 'rubocop-rspec', require: false
gem 'simplecov', require: false, group: :test
